import { LicenseEvent, Project, LicenseCategory } from './types';

export const PROJECTS: (Project | '全部')[] = [
  '全部', 
  '竹山專案', 
  '太陽能專案', 
  '深水池專案',
  '南港專案',
  '內湖商辦工程',
  '中壢擴建案',
  '高雄駁二維護',
  '新板特區開發',
  '閒置人員'
];

export const CATEGORIES: (LicenseCategory | '全部')[] = [
  '全部',
  '工安職安衛',
  '作業主管',
  '機具操作',
  '工程品管',
  '機電環保',
  '特殊作業',
];

export const MOCK_DATA: LicenseEvent[] = [
  {
    id: '1',
    name: '王大明',
    licenseName: '屋頂作業主管',
    issueDate: new Date('2023-05-20'),
    expiryDate: new Date('2026-05-20'),
    project: '竹山專案',
    category: '作業主管',
    previousRecertification: '2023/05/20 於台中職訓中心',
    notes: '正本已在工地辦公室存檔',
    attachmentName: 'roof_license_wm.pdf',
  },
  {
    id: '2',
    name: '陳小華',
    licenseName: '急救人員',
    issueDate: new Date('2023-05-25'),
    expiryDate: new Date('2026-05-25'),
    project: '太陽能專案',
    category: '工安職安衛',
    previousRecertification: '2023/05/25 於紅十字會',
    notes: '需確認是否需更換新版證照',
  },
  {
    id: '3',
    name: '林阿水',
    licenseName: '高空工作車操作',
    issueDate: new Date('2023-06-02'),
    expiryDate: new Date('2026-06-02'),
    project: '深水池專案',
    category: '機具操作',
    previousRecertification: '2023/06/02 於基隆職訓局',
    attachmentName: 'high_work_car.jpg',
  },
  {
    id: '4',
    name: '張志明',
    licenseName: '甲種職業安全衛生業務主管',
    issueDate: new Date('2023-05-10'),
    expiryDate: new Date('2026-05-10'),
    project: '竹山專案',
    category: '工安職安衛',
    previousRecertification: '2023/05/10 於台北職訓中心',
    notes: '核心管理人員',
  },
  {
    id: '5',
    name: '李大同',
    licenseName: '營造業工地主任',
    issueDate: new Date('2023-06-15'),
    expiryDate: new Date('2026-06-15'),
    project: '太陽能專案',
    category: '工安職安衛',
    previousRecertification: '2023/06/15 於營造公會',
    notes: '回訓公文已發送',
  },
  {
    id: '6',
    name: '許自強',
    licenseName: '乙級職業安全衛生管理員',
    issueDate: new Date('2024-03-10'),
    expiryDate: new Date('2027-03-10'),
    project: '閒置人員',
    category: '工安職安衛',
    previousRecertification: '2024/03/10 新取得證照',
    notes: '暫無固定派駐工地，可隨時支援新開工專案',
  },
  {
    id: '7',
    name: '黃茂雄',
    licenseName: '重機械操作-挖掘機',
    issueDate: new Date('2023-11-20'),
    expiryDate: new Date('2026-11-20'),
    project: '閒置人員',
    category: '機具操作',
    previousRecertification: '2023/11-20 於職訓協會',
    notes: '前一案結束，目前於總公司待命派遣中',
  }
];
